#!/bin/bash

#set postgres and hammerdb paths
export PGINST=/data/kuntal.ghosh/Postgresql/pg/postgresql/install/
export HDBINST=/data/kuntal.ghosh/Postgresql/HammerDB-3.2/

# Template to run hammaer db tests

# You can add postgresql parameters here
read -r -d '' VAR << EOM
# Add postgresql parameters here
shared_buffers = 100GB
max_connections = 200
min_wal_size = 20GB
max_wal_size = 40GB
checkpoint_timeout = 900
maintenance_work_mem = 1GB
checkpoint_completion_target = 0.9
synchronous_commit = on
log_checkpoints = on
EOM
export PG_OPTIONS=$VAR
cd HammerDB
./run_hammerdb
cd ..

# Template to run pgbench tests

# You can add postgresql parameters here
read -r -d '' VAR << EOM
# Add postgresql parameters here
shared_buffers = 100GB
max_connections = 200
min_wal_size = 20GB
max_wal_size = 40GB
checkpoint_timeout = 900
maintenance_work_mem = 1GB
checkpoint_completion_target = 0.9
synchronous_commit = on
log_checkpoints = on
EOM
export PG_OPTIONS=$VAR
cd PGBench
./run_pgbench
cd ..

#Add more tests here
